image:
 - Visual Studio 2019
 - macos


environment:
 matrix:
  - image: Visual Studio 2019
    GENERATOR: "Visual Studio 16"
  - image: macos
    GENERATOR: "Unix Makefiles"


matrix:
  fast_finish: true


build_script:
- mkdir build
- cd build
- cmake .. -G "%GENERATOR%"
- cmake --build . --config "Debug"
