
# - Set the environment 2-JOBS Windows / MacOS

environment:
  matrix:

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: MacOs build
    appveyor_build_worker_image: MacOs

matrix:
  fast_finish: false

init:
  - appveyor version

# - JOB-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows build
          GENERATOR: "Visual Studio 16"

    build_script:
    - echo This is Windows-specific build script
    - echo %GENERATOR%

  -
    matrix:
      only:
        - job_name: MacOs build
          GENERATOR: "Unix Makefiles"

build_script:
- echo "%GENERATOR%"
- mkdir build
- cd build
- cmake .. -G "%GENERATOR%"
- cmake --build . --config "Debug"
