image:
 - macos
 - Visual Studio 2019

matrix:
    only:
      - image: Visual Studio 2019
        environment: generator: "Visual Studio 16"

matrix:
    only:
      - image: macos
        environment: generator: "Unix Makefiles"

build_script:
- mkdir build
- cd build
- echo %generator%
- cmake .. -G %generator%
- cmake --build . --config "Debug"
