
# - Set the environment 3-cases Windows/Ubuntu/MacOS

environment:
  matrix:
    - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
      GENERATOR: "Visual Studio 15"
    - APPVEYOR_BUILD_WORKER_IMAGE: Ubuntu
      GENERATOR: "Unix Makefiles"
    - APPVEYOR_BUILD_WORKER_IMAGE: macOS
      GENERATOR: "Unix Makefiles"

#matrix:
#  fast_finish: true


build_script:
- mkdir build
- cd build
- cmake .. -G "%GENERATOR%"
- cmake --build . --config "Debug"
