
# - Set the environment 2-JOBS Windows / MacOS

environment:
  matrix:

  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: MacOs build
    appveyor_build_worker_image: MacOs

matrix:
  fast_finish: false

init:
  - appveyor version

# - JOB-specific configurations
for:

  -
    matrix:
      only:
        - job_name: Windows build
          GENERATOR: "Visual Studio 15"

    build_script:
    - cmd: echo This is Windows-specific build script
    - echo %GENERATOR%

  -
    matrix:
      only:
        - job_name: MacOs build
          GENERATOR: "Unix Makefiles"

    build_script:
    - sh: echo This is MacOs-specific build script
    - echo %GENERATOR%
