image:
 - macos
 - Visual Studio 2019

environment:
  matrix:
    - generator: "Visual Studio 16"
    - generator: "Unix Makefiles"

build_script:
- mkdir build
- cd build
- cmake .. -G generator
- cmake --build . --config "Debug"
