
environment:
  matrix:
  - job_name: Windows build
    appveyor_build_worker_image: Visual Studio 2019

  - job_name: MacOS build
    appveyor_build_worker_image: macos

matrix:
  allow_failures:
    - job_name: Windows build

for:
-
  matrix:
    only:
      - job_name: MacOS build
  build_script:
  - echo MacOs build script
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - cmake --build . --config "Debug"
  - ls

-
  matrix:
    only:
      - job_name: Windows build

  build_script:
  - echo Windows build script
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16"
  - cmake --build . --config "Debug"
  - dir



