image:
 - Visual Studio 2017
 - Ubuntu

environment:
  matrix:
    - ARCH: arm
    - ARCH: arm64
    - ARCH: amd64

matrix:
  exclude:
    - image: Visual Studio 2017
      ARCH: arm
    - image: Visual Studio 2017
      ARCH: arm64


build_script:
- mkdir build
- cd build
- cmake ..
- cmake --build . --config "Debug"
