image:
 - Visual Studio 2019
 - macos



for:
-
  matrix:
    only: 
      - image: Visual Studio 2019
    - GENERATOR: "Visual Studio 16"
  

matrix:
  fast_finish: true


build_script:
- mkdir build
- cd build
- cmake .. -G "%GENERATOR%"
- cmake --build . --config "Debug"
