image:
  - Visual Studio 2019
  - macos

for:
-
  matrix:
    only:
      - image: macos
  build_script:
  - echo MacOs build script
  - mkdir build && cd build
  - cmake .. -G "Unix Makefiles"
  - cmake --build . --config "Debug"
  - ls

-
  matrix:
    only:
      - image: Visual Studio 2019
    allow_failures:
      - image: Visual Studio 2019

  build_script:
  - echo Windows build script
  - mkdir build
  - cd build
  - cmake .. -G "Visual Studio 16"
  - cmake --build . --config "Debug"
  - dir



