image:
 - macos
 - Visual Studio 2019

environment:
  matrix:
    - generator: "Visual Studio 16"

matrix:
  fast_finish: true


build_script:
- mkdir build
- cd build
- echo %generator%
- echo %dsed%
- echo "%generaator%"
- echo generator
- cmake .. -G "%generator%""
- cmake --build . --config "Debug"
