image:
 - macos
 - Visual Studio 2019

for:
-
  matrix:
    only:
      - image: Visual Studio 2019
        generator: "Visual Studio 16"

      - image: macos
        generator: "Unix Makefiles"

build_script:
- mkdir build
- cd build
- cmake .. -G %generator%
- cmake --build . --config "Debug"
